### PR TITLE
todoItem should be deleted if updated text is blank

### PR DESCRIPTION
**Pull request by transedward**
as title said,
I think changing to this behavior would be better, only a minor fix

### CODE REVIEW

**Comment by transedward** [comment]
done!

**Comment by andrewimm** [comment]
Sounds like a good change. Could you match the coding style of the rest of the repository by including spaces in the `if` and `else` lines, so that
```
if(this.state.editText){
```
becomes
```
if (this.state.editText) {
```
and
```
}else{
```
becomes
```
} else {
```

**Comment by transedward** [comment]
done!

**Comment by andrewimm** [comment]
Thanks!

**Pull request merged**
