### PR TITLE
Provide a StubReact module to bridge 'react' vs 'react-native' difference

### PR DESCRIPTION
**Pull request by philikon**
Doing this will let us use `ParseComponent` in React Native apps.

### CODE REVIEW

**Comment by andrewimm** [comment]
I think this might upset Browserify / Webpack. I have some test builds that I run with each packager whenever we release, but I expect we will need to add
```json
browser: {
  'react-native': false
}
```
to package.json. I'm surprised the RN bundler didn't freak out about not being able to find `'react'`

**Comment by philikon** [comment]
> I'm surprised the RN bundler didn't freak out about not being able to find `'react'`

Sigh, I forgot to `-a` in my commit... Updated patch coming up.

**Comment by philikon** [comment]
> I have some test builds that I run with each packager whenever we release

It'd be good if we could document these, as well as how to run the jest tests, etc. in `CONTRIBUTING.md`.

**Comment by andrewimm** [comment]
:+1:, it's just been difficult to formalize these tests into something that we can easily run from the command line. I'd like to get it into the Travis builds, I've just been struggling to find the time to clean it up

**Comment by philikon** [comment]
I think we probably want
```json
browser: {
  "react": false,
  "react-native": false
}
```
no? Because so far we haven't listed either `react` nor `react-native` as a dependency... With that in place, browserify can package both `index.js` and `class.js`...

**Comment by andrewimm** [comment]
We don't want to include `react` in the `browser` field: when browserify / webpack encounters a package from that field, it replaces it with an empty object. We only want those packagers to ignore `react-native`.
If a developer is using this library in a larger project, the packagers will find their `react` package, and will throw if they are using `class.js` without ever using React (which shouldn't ever happen, so an exception is desired behavior there).

**Comment by philikon** [comment]
Gotcha. Fixed.

**Pull request merged**
