### PR TITLE
Fix cases when sourceVal is undefined

### PR DESCRIPTION
**Pull request by flovilmart**
With the latest update the sourceVal value can be undefined and checking against sourceVal.__type would fail

### CODE REVIEW

**Comment by flovilmart** [comment]
@andrewimm I guess this one can be closed as you fixed it with #078592db9d1fc4b223fa21d6ea00e867263c3f02

**Comment by andrewimm** [comment]
Ah, yes. I caught this when I added some extra static typing to the 0.2.3 changes. Thanks for the contribution though. If you come across any other issues, don't hesitate to create a PR to fix them.

**Comment by flovilmart** [comment]
I’m working on another nasty one, ObjectStore not releasing the subscriptions and crashing in UpdateChannel.pushUpdates

**Comment by andrewimm** [comment]
Cool. When you do finish that up, please also accept the Facebook contributor agreement so we can merge the PR

**Comment by flovilmart** [comment]
That should be good on that side:




https://github.com/ParsePlatform/ParseReact/pull/35

**Pull request closed without merging**
