### PR TITLE
Provide a declarative API equivalent of `Parse.Query(...).get()`

### PR DESCRIPTION
**Pull request by philikon**
This should address #43. I'm not attached to the method name `.one()` at all, feel free to suggest alternatives.

### CODE REVIEW

**Comment by philikon** [comment]
I'll provide a commit including a `gulp` run once #79 is merged.

**Comment by andrewimm** [comment]
Naming suggestion: since this is only used for observations, how about we adopt an `observeX` scheme? `.observeOne(id)`, `.observeCount()`, etc. for these one-off observations.

**Comment by philikon** [comment]
Yes, I like it!

**Comment by philikon** [comment]
So for this, it would mean `observeGet()`, yes? Since it's the equivalent to `Parse.Query(...).get()`

**Comment by andrewimm** [comment]
sounds awkward to me, I like observeOne better. VerbNoun vs VerbVerb

**Comment by philikon** [comment]
Yeah, I like `observeOne` better too... Just wasn't sure how strictly we wanted to follow the `observeX` rule, where `x` was the equivalent `Parse.Query` method.

**Comment by andrewimm** [comment]
I'll be cutting a new v0.4 release after merging these changes

**Pull request merged**
